version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Frontend port mapping
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"  # Backend port mapping
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todolist

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"  # PostgreSQL port mapping
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: